### ISSUE TITLE
Persistent Volume Claim unbounded 

### ISSUE THREAD

**Issue by Maya-kassis** [mora-resource-allocation-edge-cloud/mora#17]
Hello,

I am trying to run the cloud with helm without minikube using the minikube branch by running the following command:

helm install vp-cloud -f variants/values.cloud.yaml --generate-name --disable-openapi-validation

The following 3 pods are in pending state; the description is "3 pod has unbound immediate PersistentVolumeClaims"
1. videoserver-gateway
2. videoserver-videomanagement
3. videoserver-videoprocessing

I am using kubectl v1.18.6; with the default case:
kubectl get sc
No resources found

kubectl get pv
foo-pv    512M       RWO,ROX,RWX    Retain           Available           standard                38h
foo-pv2   5Gi        RWO,ROX,RWX    Retain           Available           standard                38h
foo-pv3   1Gi        RWO,ROX,RWX    Retain           Available           standard                38h
foo-pv4   5Gi        RWO,ROX,RWX    Retain           Available           standard                38h

kubectl get pvc
mongodb-data             Pending                                                     38h
videoserver-logs         Pending                                                     38h
videoserver-video        Pending                                                     38h
videoserver-videofiles   Pending                                                     38h

Good links to be saved:
https://kubernetes.io/blog/2017/03/dynamic-provisioning-and-storage-classes-kubernetes/

In our prototype related to kube5g; we did not need to create a storage class; please advise if there is a need to create SC in this case.
Thanks in advanced.

**Comment by aleskandro** [comment]
Yes, as some Deployment uses volumes, we need to have some solution for storage.

Can I ask for the installation process of your kubernetes flavour? In order to support, I'd have the best possible description of its deployment scenario/configuration.

**Comment by aleskandro** [comment]
Please Maya, can you provide me the result of:

`kubectl describe pv foo-pv`
`kubectl describe pvc mongodb-data`

Also use the triple "```" to enclose code/commands result , so that it can result more readable here.

**Comment by aleskandro** [comment]
And also, can you provide more detail about the installation process and architecture of your kube5g?

**Comment by aleskandro** [comment]
@zazim13 
https://github.com/mora-resource-allocation-edge-cloud/deployment/blob/85753f4f4c1b68efc169527bdffdb967034391e9/vp-cloud/templates/07-pv.yaml

This file create a few persistent volumes on the cluster you are deploying.

- [ ] However, HostPath persistent volumes are only for minikube. So, an if to check `.Values.isMinikube` should be added to enclose the entire file.

**Comment by Maya-kassis** [comment]
```
kubectl describe pv foo-pv
"Name:            foo-pv
Labels:          app.kubernetes.io/managed-by=Helm
Annotations:     meta.helm.sh/release-name: vp-cloud-1627153033
                 meta.helm.sh/release-namespace: default
Finalizers:      [kubernetes.io/pv-protection]
StorageClass:    standard
Status:          Available
Claim:           
Reclaim Policy:  Retain
Access Modes:    RWO,ROX,RWX
VolumeMode:      Filesystem
Capacity:        512M
Node Affinity:   <none>
Message:         
Source:
    Type:          HostPath (bare host directory volume)
    Path:          /var/cloud/mongodata
    HostPathType:  DirectoryOrCreate
Events:            <none> "
```
---------------------------------------------------------------------
```
kubectl describe pvc mongodb-data
"Name:          mongodb-data
Namespace:     default
StorageClass:  
Status:        Pending
Volume:        
Labels:        app.kubernetes.io/managed-by=Helm
Annotations:   meta.helm.sh/release-name: vp-cloud-1627153033
               meta.helm.sh/release-namespace: default
Finalizers:    [kubernetes.io/pvc-protection]
Capacity:      
Access Modes:  
VolumeMode:    Filesystem
Mounted By:    <none>
Events:
  Type    Reason         Age                      From                         Message
  ----    ------         ----                     ----                         -------
  Normal  FailedBinding  2m32s (x10605 over 44h)  persistentvolume-controller  no persistent volumes available for this claim and no storage class is set"

```

**Comment by Maya-kassis** [comment]
On the cluster, after apply CRD to k8s cluster
I deploy the following yaml file
https://gitlab.eurecom.fr/mosaic5g/kube5g/-/blob/workshop-dec-2020/openshift/kube5g-operator/deploy/crds/cr-v2/lte-with-flexran/mosaic5g_v1alpha1_cr_v2_lte_flexran.yaml

This create one pod for each of the following components, in addition to the kube5g-operator
1. RAN
2. FlexRAN
3. HSS
4. MME
5. Cassandra DB
6. SPGWU
7. SPGWC

**Comment by aleskandro** [comment]
We made a call with @Maya-kassis . She will deploy a storage class and the provisioner based on nfs.

- [X] @zazim13 you should set a new key in the values.yaml

I'd say `storageClass`.

- [X] Use it in the [pvcs template](https://github.com/mora-resource-allocation-edge-cloud/deployment/blob/85753f4f4c1b68efc169527bdffdb967034391e9/vp-cloud/templates/06-pvc.yaml).

- [X]  Fix the mongodb volume to also use a PVC (currently the deployment is statically bound to a hostpath volume which is not feasible in  kube5g)

**Comment by Maya-kassis** [comment]
I tried to create ingress service, ingress controller and I add the created NFS storage class to the PV and PVC yaml  files as  storageClassName: "nfs-client" 

Now I see all the pods are running; but the pod  videoserver-videomanagement is running as 0/1, in the description
Readiness probe failed: Get http://10.244.6.28:8080/ping: net/http: request canceled (Client.Timeout exceeded while awaiting headers)
Readiness probe failed: Get http://10.244.6.28:8080/ping: dial tcp 10.244.6.28:8080: connect: connection refused

```
PV yaml file
apiVersion: v1
kind: PersistentVolume
metadata:
  name: foo-pv
spec:
  storageClassName: "nfs-client"
  accessModes:
    - ReadWriteMany
    - ReadWriteOnce
    - ReadOnlyMany
  capacity:
    storage: 512M
  hostPath:
    path: /var/cloud/mongodata
    type: DirectoryOrCreate
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: foo-pv3
spec:
  storageClassName: "nfs-client"
  accessModes:
    - ReadWriteMany
    - ReadWriteOnce
    - ReadOnlyMany
  capacity:
    storage: 1Gi
  hostPath:
    path: /var/cloud/logs
    type: DirectoryOrCreate
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: foo-pv2
spec:
  storageClassName: "nfs-client"
  accessModes:
    - ReadWriteMany
    - ReadWriteOnce
    - ReadOnlyMany
  capacity:
    storage: 5Gi
  hostPath:
    path: /var/cloud/videos
    type: DirectoryOrCreate
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: foo-pv4
spec:
  storageClassName: "nfs-client"
  accessModes:
    - ReadWriteMany
    - ReadWriteOnce
    - ReadOnlyMany
  capacity:
    storage: 5Gi
  hostPath:
    path: /var/cloud/videofiles
    type: DirectoryOrCreate
-----------------------------------------------------------------------------------------------------------------------------------------------------------

PVC yaml file:
apiVersion: "v1"
kind: "PersistentVolumeClaim"
metadata:
  name: "videoserver-videofiles"
spec:
  storageClassName: "nfs-client"
  accessModes:
    - "ReadWriteMany"
  resources:
    requests:
      storage: "5Gi"
---
apiVersion: "v1"
kind: "PersistentVolumeClaim"
metadata:
  name: "videoserver-logs"
spec:
  storageClassName: "nfs-client"
  accessModes:
    - "ReadWriteMany"
  resources:
    requests:
      storage: "1Gi"
---
apiVersion: "v1"
kind: "PersistentVolumeClaim"
metadata:
  name: "videoserver-video"
spec:
  storageClassName: "nfs-client"
  accessModes:
    - "ReadWriteMany"
  resources:
    requests:
      storage: "5Gi"
---
apiVersion: "v1"
kind: "PersistentVolumeClaim"
metadata:
  name: "mongodb-data"
spec:
  storageClassName: "nfs-client"
  accessModes:
    - "ReadWriteOnce"
  resources:
    requests:
      storage: "512M"
```
