### ISSUE TITLE
Verify/Fix creation of the capped collection in the Edge Variant

### ISSUE THREAD

**Issue by aleskandro** [mora-resource-allocation-edge-cloud/mora#2]
In the helm template, the creation of the capped collection must be achieved by a one-shot job at the deployment stage.

In particular, the job has to use Mongo credentials available in the secrets and configmaps already used by the VMS and the MongoDB deployments.

The job will create the capped collection using a 1-line shell script.

## Implementation hints

Use the [mongoclient/mongoclient](https://hub.docker.com/r/mongoclient/mongoclient/) image for the job and the following command:

```sh
mongo $MONGODB_HOST:$MONGODB_PORT/$MONGODB_DATABASE -u $MONGODB_USER -p $MONGODB_PASSWORD \
--eval="db.createCollection('video', {
   capped: true, 
  size: {{ .Values.mongo.videoCollectionSize }}, 
  max: {{ .Values.mongo.videoCollectionMaxDocs }} 
})"
```

where: 

`{{ .Values.mongo.videoCollectionSize }}` and `{{ .Values.mongo.videoCollectionMaxDocs }}` are replaced by the (provided) helm values file.

Finally, this job has to be deployed only if the helm boolean `isCloud` is set to `false`.

**Comment by zazim13** [comment]
Hi @aleskandro . The video collection was not created automatically in the edge because the edge was not able to download any video from the cloud. In fact the java application (In the edge) was not able to resolve cloud-vms-1.master.particles.dieei.unict.i to an ip address. I solved the problem by adding the configuration HostAliases in the vms config file. (It will add entries to pod /etc/hosts ). 
I just pushed changes in minikubebranch. 
[see this link to the specific line](https://github.com/mora-resource-allocation-edge-cloud/deployment/blob/fa93ab2076c9b9a9c49617ca368db832fc70cc85/vp-cloud/templates/02-videomanagement.yml#L24)

Now,  when a video is only available in the cloud and that I ask the edge this video, a video collection is created in the edge if not already created before. This operation is done in the code somewhere (I have to find which part of the code does that).

The problem that the collection created as above is not capped.

I have also implemented the mongoclient. It can connect to mongodb and send requests (through a web interface). Next step will be to automate the creation of the capped collection at deployment. Or turn an existing video collection to a capped collection.
I will keep you updated.

**Comment by aleskandro** [comment]
Hi @zazim13, we cannot use static ips in that line. Please, remove it.

Actually, from a network perspective:

- `cloud-vms-1.master.particles.dieei.unict.it` has to be changed into cloudmora.eu which is registered, has globally available nameservers related to it and a well-defined dns zone that get us able to reach videos in the "cloud variant". So, we can just modify the default `values.yaml` file replacing that url with the new one: `s/cloud-vms-1.master.particles.dieei.unict.it/cloudmora.eu/`. I do not know which service are you reaching by 172.16.0.43. But probably, when we'll deploy somewhere else the software it will not be able to reach this private address. Finally, if that address is currently related to the nginx k8s service of the cloud variant, whenever we'll delete the service and re-apply it, it is not guaranteed that this ip will be still the right one. hostnames are used, overall, for this reason.
- Any "edge variant" (offline, cache, online...) will be able to download videos from the cloud version
- Yes, the created collection is not capped: moreover, to my knowledge we cannot convert a "standard" collection into a "capped" collection after its creation.

So I would suggest again to add a job in the helm template to be deployed only if isCloud is set to false. This job will create the collection with the command in the description of the issue. Any other problem, like the "hostname reachabilty" of the cloud variant, maybe, would be better described in the readme.

**Comment by aleskandro** [comment]
a new file, like the following one (to be fixed/verified, maybe the command definition could be bugged) should work:

```yaml
{{ if eq .Values.isCloud true }}
apiVersion: batch/v1
kind: Job
metadata:
  name: create-collection-{{ now | date "20060102150405" }}
spec:
  completions: 1
  backoffLimit: 3
  parallelism: 1
  ttlSecondsAfterFinished: 3600
  template:
    metadata:
      labels:
        job: create-collection
    spec:
      restartPolicy: OnFailure
      containers:
        - name: collection-create
          image: mongoclient/mongoclient 
          command:
            - sh
            - -c
            - "mongo  {{ .Values.mongodb.serviceName }}:27017/$MONGODB_DATABASE -u $MONGODB_USERNAME -p $MONGODB_PASSWORD --eval=\"db.createCollection('video', {capped: true,   size: {{ .Values.mongo.videoCollectionSize }},   max: {{ .Values.mongo.videoCollectionMaxDocs }} })\""
           - env:
             - name: MONGODB_USERNAME
               value: {{ .Values.mongodb.username }}
             - name: MONGODB_PASSWORD
               value: {{ .Values.mongodb.password }}
             - name: MONGODB_ADMIN_PASSWORD
               value: {{ .Values.mongodb.password }}
             - name: MONGODB_DATABASE
               value: {{ .Values.mongodb.databaseName }}
{{- end }}
```

- the name also has a timestamp as a workaround since jobs in kubernetes are immutable and an upgrade command could fail (better solutions are welcome).
- the command could not work correctly just because of the array definition.
- there is a MONGODB_ADMIN_PASSWORD defined in the mongodb deployment. Not sure whether if we have to use MONGODB_PASSWORD or MONGODB_ADMIN_PASSWORD. Just check what the VMS does.
- Completion is set to 1 since we need just one completion for the job
- backoffLimit is set to 3 just as to retry the job 3 times before considering it failed.
- ttlSecondsAfterFinished just remove the job from the kubernetes history after 1-hout it finished
- maybe, in this case, we do not need neither the deletion of the job nor that workaround to differentiate him between "helm upgrades": if we make once the creation of the collection, it will not be needed during upgrades of the same env. So, maybe we can remove the ttlSecondsAfterFinished and the second part of the job name. Just need to be verified.
