### ISSUE TITLE
Add support for defining resources limits and requests and replicas number on the helm template

### ISSUE THREAD

**Issue by aleskandro** [mora-resource-allocation-edge-cloud/mora#9]
For each deployment object we need to add support for defining limits and requests in the values.yml file of the helm template.

In particular, the resources will depend on the specific variant-option pair, i.e., we shall configure requests and limits for containers [1] based on the settings of the variant and of its specific option.

## List of the deployments objects

- VMS
- VPS
- MongoDB
- API Gateway
- Load Balancer

All these deployment must have requests and limits defined in the default values.yaml file.

## Implementation hints

We can implement it by adding these map:

```yaml

resources:
  vms:
     limits: 
        cpu: ...
        memory: ....
     requests:
       cpu: ...
        ....
  vps:
      .... as above ...

  ... for each deployment in the list above ...
```

Then, for each deployment, in the container specs we can add:

```yaml
spec:
 replicas: .Values.vms.replicas
 containers:
    - name: vms
      image: images.my-company.example/app:v4
      resources:
      {{- .Values.resources.vms | toYaml | nindent $fix_here }}
```

## Example

At the end of this implementation we'll be able, given a specific variant,  to define multiple options with different requirements.
Let's consider  the edge-cache variant, we can define a values.yaml file that define an option as:

```yaml
utility: 1024
lb:
  maxConcurrentUsers: 100
vms:
  replicas: 2
  isCloud: "false" # Let the micro-services know they are executing in the Edge
  maxVideo: 10 # Set limits of the capped collection (i.e., the maximum number of video stored in the Edge, leveraging a LRU cache retention policy)
  variantType: "0" # Set the VMS to act as the Edge Cache Variant
  needKafkaBeans: "false"

resources:
  vms: 
     limits: 
       cpu: 100m
       memory: 1Gi

    requests:
      cpu: 50m
      memory: 700M
   ...


```

In this case, we deploy the edge-cache variant with 2 replicas of the VMS and resource requirements for the VMS of 200m CPUs and 2Gi memory.

We should add to these resource requirements, the ones of the other pods deployed: I'm not reporting them cause are exactly of the same form.

The total requirements will represent resources required by the given option (variant + option). Together with the utility value (not used by any k8s object) of this option we can instruct the scheduler and the orchestrator to decide which options to deploy (see [2]).

## References

- [1] https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/
- [2] https://dl.acm.org/doi/abs/10.1145/3341105.3374026
